---
title: "R Notebook"
output: html_notebook
---
R Studio API Code
```{r}
library(rstudioapi)
setwd(dirname(getActiveDocumentContext()$path))
```

Libraries
```{r}
library(tidyverse)
library(ggplot2)
library(lubridate)
```

Data Import 
```{r}
week9_tbl <- as_tibble(read_csv("../data/week3.csv"))
  
week9_tbl_clean <- week9_tbl %>%
  mutate(timeStart=ymd_hms(timeStart),
         gender=factor(gender,levels=c("M","F"),labels=c("Male","Female")),
         condition=factor(condition,levels=c("A","B","C"), labels=c("Block A","Block B","Control")),
         Q1Q5means =rowMeans(week9_tbl[5:9]),
         Q6Q10means=rowMeans(week9_tbl[10:14])) %>%
  filter(q6==1)
```
Visualization 
```{r}
ggplot(week9_tbl_clean, aes(Q1Q5means, Q6Q10means))+
  geom_point() + 
  geom_smooth(method="lm", se=FALSE)+
  labs(x="Mean of Q1 to Q5",
       y="Mean of Q6 to Q10",
       title="Mean of Q1 to Q5 versus Mean of Q6 to Q10")
```

Analysis 
```{r}
mean_cor <- cor.test(week9_tbl_clean$Q1Q5means, week9_tbl_clean$Q6Q10means)
mean_cor$estimate
mean_cor$p.value
```
